name: Synchronize to main
on:
  push:
    branches-ignore:
      - main

jobs:
  branch-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-${{ github.ref_name }}
          base: main
          title: 'Sync changes from ${{ github.ref_name }} to main'
          body: 'Automated PR to sync changes from ${{ github.ref_name }} to main'
          delete-branch: true

      - name: Auto-merge Pull Request
        run: |
          PR_NUMBER=$(gh pr list --json number --jq '.[0].number')
          if [ ! -z "$PR_NUMBER" ]; then
            gh pr merge $PR_NUMBER --merge --auto
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
